/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperadminRouteImport } from './routes/superadmin'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as SSubdomainRouteImport } from './routes/s.$subdomain'
import { Route as DashboardProductsRouteImport } from './routes/dashboard.products'
import { Route as DashboardMembershipRouteImport } from './routes/dashboard.membership'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as ApiPublicSyncKrincesaRouteImport } from './routes/api/public/sync-krincesa'
import { Route as ApiPublicCheckSubscriptionsRouteImport } from './routes/api/public/check-subscriptions'

const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const SSubdomainRoute = SSubdomainRouteImport.update({
  id: '/s/$subdomain',
  path: '/s/$subdomain',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProductsRoute = DashboardProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMembershipRoute = DashboardMembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiPublicSyncKrincesaRoute = ApiPublicSyncKrincesaRouteImport.update({
  id: '/api/public/sync-krincesa',
  path: '/api/public/sync-krincesa',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCheckSubscriptionsRoute =
  ApiPublicCheckSubscriptionsRouteImport.update({
    id: '/api/public/check-subscriptions',
    path: '/api/public/check-subscriptions',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/superadmin': typeof SuperadminRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/membership': typeof DashboardMembershipRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/s/$subdomain': typeof SSubdomainRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/check-subscriptions': typeof ApiPublicCheckSubscriptionsRoute
  '/api/public/sync-krincesa': typeof ApiPublicSyncKrincesaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/superadmin': typeof SuperadminRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/membership': typeof DashboardMembershipRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/s/$subdomain': typeof SSubdomainRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/public/check-subscriptions': typeof ApiPublicCheckSubscriptionsRoute
  '/api/public/sync-krincesa': typeof ApiPublicSyncKrincesaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/superadmin': typeof SuperadminRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/membership': typeof DashboardMembershipRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/s/$subdomain': typeof SSubdomainRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/check-subscriptions': typeof ApiPublicCheckSubscriptionsRoute
  '/api/public/sync-krincesa': typeof ApiPublicSyncKrincesaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/onboarding'
    | '/superadmin'
    | '/dashboard/analytics'
    | '/dashboard/membership'
    | '/dashboard/products'
    | '/s/$subdomain'
    | '/dashboard/'
    | '/api/public/check-subscriptions'
    | '/api/public/sync-krincesa'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/superadmin'
    | '/dashboard/analytics'
    | '/dashboard/membership'
    | '/dashboard/products'
    | '/s/$subdomain'
    | '/dashboard'
    | '/api/public/check-subscriptions'
    | '/api/public/sync-krincesa'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/onboarding'
    | '/superadmin'
    | '/dashboard/analytics'
    | '/dashboard/membership'
    | '/dashboard/products'
    | '/s/$subdomain'
    | '/dashboard/'
    | '/api/public/check-subscriptions'
    | '/api/public/sync-krincesa'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  SuperadminRoute: typeof SuperadminRoute
  SSubdomainRoute: typeof SSubdomainRoute
  ApiPublicCheckSubscriptionsRoute: typeof ApiPublicCheckSubscriptionsRoute
  ApiPublicSyncKrincesaRoute: typeof ApiPublicSyncKrincesaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/s/$subdomain': {
      id: '/s/$subdomain'
      path: '/s/$subdomain'
      fullPath: '/s/$subdomain'
      preLoaderRoute: typeof SSubdomainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/products': {
      id: '/dashboard/products'
      path: '/products'
      fullPath: '/dashboard/products'
      preLoaderRoute: typeof DashboardProductsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/membership': {
      id: '/dashboard/membership'
      path: '/membership'
      fullPath: '/dashboard/membership'
      preLoaderRoute: typeof DashboardMembershipRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/public/sync-krincesa': {
      id: '/api/public/sync-krincesa'
      path: '/api/public/sync-krincesa'
      fullPath: '/api/public/sync-krincesa'
      preLoaderRoute: typeof ApiPublicSyncKrincesaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/check-subscriptions': {
      id: '/api/public/check-subscriptions'
      path: '/api/public/check-subscriptions'
      fullPath: '/api/public/check-subscriptions'
      preLoaderRoute: typeof ApiPublicCheckSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardMembershipRoute: typeof DashboardMembershipRoute
  DashboardProductsRoute: typeof DashboardProductsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardMembershipRoute: DashboardMembershipRoute,
  DashboardProductsRoute: DashboardProductsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  SuperadminRoute: SuperadminRoute,
  SSubdomainRoute: SSubdomainRoute,
  ApiPublicCheckSubscriptionsRoute: ApiPublicCheckSubscriptionsRoute,
  ApiPublicSyncKrincesaRoute: ApiPublicSyncKrincesaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
